[PrivateAEYE]
api_url = "http://localhost:5002"
project_name = "TestContainer"
project_repo = "gpigc-2025/testcontainer"
check_url = "http://172.19.0.5:5005"

[WikAI]
api_url = "http://localhost:5001"
project_name = "TestContainer"
